version: 2

# 빌드 설정
build:
  os: ubuntu-20.04  # 사용할 OS 이미지 지정 (예: ubuntu-20.04)
  image: "latest"   # 최신 버전 이미지 사용
  tools:
    sphinx:  # 'sphinx'를 도구 이름으로 사용
      version: "4.0"  # 사용하고자 하는 Sphinx 버전 (필요에 맞게 변경 가능)
  commands:
    - pip install -r requirements.txt  # 필요 패키지 설치 (requirements.txt에 있는 패키지들)
    - sphinx-build -b html docs/source docs/build  # Sphinx 빌드 명령어

# Python 버전 설정
python:
  version: 3.12.2  # 필요한 Python 버전 지정
  install:
    - requirements: requirements.txt

# Sphinx 설정
sphinx:
  configuration: docs/source/conf.py