version: 2

sphinx:
  configuration: docs/source/conf.py  # Path to your Sphinx configuration file

python:
  version: 3.8  # Specify the Python version you are using
  install:
    - requirements: docs/requirements.txt  # If you have a requirements.txt file
  os: ubuntu-20.04  # Make sure you specify the OS you're building for

build:
  os: ubuntu-20.04  # Specify the OS if it's not already defined

