version: 2

build:
  os: ubuntu-20.04
  image: "latest"  # 최신 버전 사용

python:
  version: 3.12.2  # 사용하는 Python 버전으로 수정 (예: 3.8, 3.9 등)
  install:
    - requirements: requirements.txt  # 필요한 패키지가 있는 경우 requirements 파일 명시

sphinx:
  configuration: docs/source/conf.py  # Sphinx 설정 파일의 위치