version: 2

# 빌드 설정
build:
  os: ubuntu-20.04  # 빌드에 사용할 OS
  tools:
    python: "3.11"  # Python 버전 3.11을 문자열로 지정
  commands:
    - pip install -r requirements.txt  # 필요 패키지 설치
    - sphinx-build -b html docs/source docs/build  # Sphinx 빌드 명령어

# Python 설정
python:
  version: "3.11"  # Python 버전 설정 (문자열로)
  install:
    - { install: "pip" }
    - { install: "sphinx" }
    - { install: "sphinx-rtd-theme" }
    - { install: "pygame==2.6.1" }
    - { install: "numpy==1.26.4" }
    - { install: "ultralytics==8.3.40" }
    - { install: "mediapipe==0.10.18" }
    - { install: "speechrecognition==3.11.0" }
    - { install: "pytesseract==0.3.13" }
    - { install: "opencv-python==4.10.0.84" }
    - { install: "Pillow==11.0.0" }

# Sphinx 설정
sphinx:
  configuration: docs/source/conf.py  # Sphinx 설정 파일 경로