version: 2

# 빌드 설정
build:
  os: ubuntu-20.04  # 빌드에 사용할 OS
  tools:
    python: "3.11"  # Python 버전 3.11을 문자열로 지정
  commands:
    - pip install -r requirements.txt  # 필요 패키지 설치
    - sphinx-build -b html docs/source docs/build  # Sphinx 빌드 명령어

# Python 설정
python:
  version: "3.11"  # Python 버전 설정 (문자열로)
  install:
    requirements: requirements.txt  # requirements.txt 파일을 참조

# Sphinx 설정
sphinx:
  configuration: docs/source/conf.py  # Sphinx 설정 파일 경로